# Generated by Django 4.2.7 on 2023-11-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cart_name_user_cart_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
