# Generated by Django 4.2.7 on 2023-11-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_cart_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart_name',
        ),
    ]
