# Generated by Django 4.2.7 on 2023-11-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_cart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
