# Generated by Django 4.2.7 on 2023-11-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_cart_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_join',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
